github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
tasks:
  - before: |
      sudo apt update -y
      sudo apt install -y php8.1-mbstring php8.1-dom php8.1-fileinfo php8.1-xdebug
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      sudo php composer-setup.php
      php -r "unlink('composer-setup.php');"
      sudo mv composer.phar /usr/bin/composer
      npm install -g npm@latest
      npm install -g markdownlint-cli
    init: |
      composer install --prefer-dist
gitConfig:
  alias.st: status
  alias.co: checkout
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - bmewburn.vscode-intelephense-client
