
tasks:
  - before: |
      sudo apt update -y
      sudo apt install -y php8.4-mbstring php8.4-dom php8.4-fileinfo php8.4-xdebug
      curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin --filename=composer
      npm install -g npm@latest
      npm install -g markdownlint-cli
    init: |
      composer install --prefer-dist
gitConfig:
  alias.st: status
  alias.co: checkout
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - bmewburn.vscode-intelephense-client
